version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Prod_Dockerfile
    container_name: 'nest-todo-prod-client'
    ports:
      - 80:80
    depends_on:
      - server
    restart: always
  server:
    # 构建目录
    build:
      context: ./server
      dockerfile: Prod_Dockerfile
    # 容器名
    container_name: 'nest-todo-prod-server'
    # 暴露端口
    expose:
      - 4200
    ports:
      - 4200:4200
    # 环境变量
    environment:
      - DOCKER_ENV=true
    restart: always
    depends_on:
      - mariadb
      - redis
  mariadb:
    image: mariadb
    container_name: 'nest-todo-mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
      MARIADB_DATABASE: 'nest_todo'
    ports:
      - 3306:3306
    restart: always
  redis:
    image: redis
    container_name: 'nest-todo-redis'
    ports:
      - 6379:6379
    restart: always